name = "freetalk-quiz-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2023-12-01"

[durable_objects]
bindings = [
  { name = "QUIZ_ROOMS", class_name = "QuizRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["QuizRoom"]