name = "freetalk-quiz"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
tag = "v2"
deleted_classes = ["QuizRoom"]

[build]
command = "npm run build:frontend"

[assets]
directory = "./apps/frontend/out"
binding = "ASSETS"