name = "freetalk-quiz-backend"
main = "apps/worker/src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "QUIZ_ROOMS", class_name = "QuizRoom" },
  { name = "ROOM_MANAGER", class_name = "RoomManager" }
]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomManager"]

[build]
command = "npm run build:worker"